name: compact_quran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  global: ^0.0.2
  get: ^4.6.6
  google_fonts: ^6.2.1
  dio: 5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  fpdart: 1.1.0
  connectivity_plus: 6.0.5
  another_flushbar: 1.12.30
  shimmer: 3.0.0
  scrollable_positioned_list: 0.3.8
  get_storage: ^2.1.1
  glass: 2.0.0+1
  url_launcher: 6.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

